# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config| 

   config.vagrant.host = "windows"
   config.vm.box_check_update = true
   config.ssh.insert_key = false

   config.vm.define "tc" do |tc|
      tc.vm.box = "centos/8"
      tc.vm.hostname = 'tc'
      tc.vm.network "private_network", ip: "192.168.56.223"
      tc.vm.provider "virtualbox" do |vb|
         vb.memory = "4096"
      end
      tc.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "/vagrant/insecure_private_key"
      tc.vm.provision "shell", inline: "chmod 0600 /vagrant/insecure_private_key"
   
      tc.vm.provision "shell", path: "root_ssh.sh"	
      tc.vm.provision "ansible_local" do |ansible|
         ansible.playbook = "playbook.yml"
         ansible.limit = "all"
         ansible.verbose = true
         ansible.install = true
      end
   end

end

