# -*- mode: ruby -*-
# vi: set ft=ruby :
num_of_be = 2
num_of_fe = 2

Vagrant.configure("2") do |config| 

   config.vagrant.host = "windows"
   config.vm.box_check_update = true
   config.ssh.insert_key = false

   config.vm.define "ts" do |ts|
      ts.vm.box = "centos/8"
      ts.vm.hostname = 'tc'
      ts.vm.network "private_network", ip: "192.168.56.223"
      ts.vm.provider "virtualbox" do |vb|
         vb.memory = "4096"
      end
      ts.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "/vagrant/insecure_private_key"
      ts.vm.provision "shell", inline: "chmod 0600 /vagrant/insecure_private_key"

      ts.vm.provision "shell", path: "root_ssh.sh"	
      ts.vm.provision "ansible_local" do |ansible|
         ansible.playbook = "playbook.yml"
         ansible.limit = "all"
         ansible.verbose = true
         ansible.install = true
      end
   end

end

